version: "3"
services: 
  
  fastapi-app:
    image: sharabhs/fastapi_celery_frontend
    ports:
      - "8080:8080"
    depends_on:
      - rabbit
      - celery-worker
      - redis-service

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=myadmin
      -  RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672"
      - "5672:5672"

  redis-service:
    hostname: redis-service
    image: redis:latest
    ports:
     - 6379:6379

  celery-worker:
    image: sharabhs/fastapi_celery_worker
    depends_on: 
      - redis-service
      - rabbit