apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: celery-worker
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 180 # Optional. Default: 300 seconds
  minReplicaCount: 1 # Optional. Default: 0
  maxReplicaCount: 10 # Optional. Default: 100
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://myadmin:password@rabbitmq.rabbit.svc.cluster.local:5672
      protocol: auto
      queueName: consumer
      queueLength: "5"