apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  host: YW1xcDovL215YWRtaW46cGFzc3dvcmRAcmFiYml0OjU2NzI=  #base64 encoded value of format amqp://guest:password@localhost:5672/vhost
  # host: 'amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672/rabbitmq'
  # host: 'amqp://myadim:password@rabbit.default.svc.cluster.local:5672'