apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f Docker-compose.yaml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: fastapi-app
  name: fastapi-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: fastapi-app
status:
  loadBalancer: {}
